version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: events-postgres
    environment:
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_pass
      POSTGRES_DB: events_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U events_user -d events_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: events_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: events_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://events_user:events_pass@postgres:5432/events_db
      REDIS_URL: redis://redis:6379/0
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./cli:/app/cli
    command:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
